apiVersion: v1
kind: Pod
metadata:
  name: pod-docker
spec:
  containers:
    - name: web
      image: nginx:1.16
      imagePullPolicy: IfNotPresent
      
      volumeMounts:
        - name: docker-cli
          mountPath: /usr/bin/docker
        - name: docker-sock
          mountPath: /var/run/docker.sock

  
  
  volumes:
    - name: docker-cli
      hostPath:
        path: /usr/bin/docker
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock

