apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
spec:
  storageClassName: "normal-storage"
  persistentVolumeReclaimPolicy: Recycle   #删除pvc后,pv会转为可用状态
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/nginx
