apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-01
spec:
  containers:
    - name: nginx
      image: nginx:1.16
      volumeMounts:
        - name: web-storage
          mountPath: /usr/share/nginx/html
  
  volumes:
    - name: web-storage
      persistentVolumeClaim:
        claimName: hostpath-pvc
