apiVersion: v1
kind: ResourceQuota
metadata:
  name: meme-cpu-demo-1
  namespace: ops
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi

    limits.cpu: "2"
    limits.memory: 2Gi
    

  
