apiVersion: v1
kind: Pod
metadata:
  name: pod-with-resourcequota
  namespace: ops
spec:
  containers:
    - name: nginx
      image: nginx:1.16
      resources:
        requests:
          cpu: "300m"
          memory: 400Mi
        limits:
          cpu: 500m
          memory: 600Mi

