apiVersion: v1
kind: Service 
metadata:
  name: demoapp-serv-nodeport
spec:
  type: NodePort
  selector:
    app: webserver
  ports:
    - name: http
      port: 8888
      targetPort: 80
      nodePort: 32000
