apiVersion: v1
kind: Service
metadata:
  name: mysql-external
spec:
  type: ClusterIP
  ports:
    - port: 3355
      targetPort: 3306




---

apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-external
subsets:
  - addresses:
      - ip: 192.168.0.51
    ports:
      - protocol: TCP
        port: 3306
