apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  replicas: 3
  serviceName: web-svc
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
             - name: data
               mountPath: /usr/share/nginx/html

  volumeClaimTemplates:
     - metadata:
         name: data
       spec:    
         accessModes: ["ReadWriteOnce"]
         storageClassName: managed-nfs-storage
         resources:
           requests:
             storage: 1Gi
