apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-required-02
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: IfNotPresent
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: zone
                    operator: NotIn 
                    values:
                      - beijing
                  - key: disktype
                    operator: NotIn
                    values:
                      - ssd
