apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-required-03
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx003
          image: nginx:1.16
          imagePullPolicy: IfNotPresent
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              preference:
                 matchExpressions:
                   - key: gpu
                     operator: Exists

