apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      type: required
  template:
    metadata:
      labels: 
        app: redis
        type: required
    spec:
      containers:
        - name: redis
          image: redis:6.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 500m
              memory: 1000Mi
  
 
