apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1000m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 400Mi
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis
                    - key: type
                      operator: In
                      values:
                        - required
                topologyKey: kubernetes.io/hostname
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis
                    - key: type
                      operator: In
                      values:
                        - required
                topologyKey: rack

