apiVersion: v1
kind: Pod
metadata:
  name: pod-redis-slave-command
spec:
  containers:
  - name: redis-slave
    image: redis
    command:
    - "redis-server"
    args:
    - --port 6380
    - --slaveof  10.1.132.39 6379
    ports:
    - containerPort: 6380

