apiVersion: v1
kind: Pod
metadata:
  name: pod-restart
spec:
  restartPolicy: Always
  containers:
  - name: nginx
    image: nginx:1.16 
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
