apiVersion: v1
kind: Pod
metadata:
  name: init-check-mysql
spec:
  restartPolicy: Always
  initContainers:
  - name: check-mysgl
    image: oldxu3957/tools
    command: ["sh", "-c", "nc -z 192.168.0.51 3306"]

  containers:
  - name: webapp
    image: tomcat
    ports:
    - containerPort: 8080
