apiVersion: v1
kind: Pod
metadata:
  name: prestop-test
spec:
  containers:
    - name: nginx
      image: nginx:1.16
      lifecycle:
        postStart:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo hello from poststart handler > /usr/share/nginx/html/index.html "
        preStop:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "nginx -s quit"
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 1000Mi
