apiVersion: v1
kind: Pod
metadata:
  name: pod-down-api
  labels:
    app: nginx-app
    role: backend
    zone: beijing
spec:
  containers:
    - name: pod-down-api
      image: nginx
      command: ["bin/sh", "-c", "env"]


      resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 200m
            memory: 1000Mi

      env:
      - name: APPXX_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: APPXX_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: APPXX_POD_LABELS
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['app']

      - name: APPXX_CPU_REQUESTS
        valueFrom:
          resourceFieldRef:
            resource: requests.cpu
            
      - name: APPXX_MEMORY_LIMITS
        valueFrom:
          resourceFieldRef:
            resource: limits.memory
            divisor: 1Mi

