apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql-env
spec:
  containers:
  - name: mysql
    image: mysql:5.7.37
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "waityou"
    - name: MYSQL_DATABASE
      value: "abc"

