apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-controll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq
  template:
    metadata:
      labels:
        app: mq
    spec:
      containers:
        - name: rabbitmq-server
          image: rabbitmq
          ports:
            - containerPort: 5672
          resources:
            limits:
              cpu: 100m
              memory: 100Mi

