apiVersion: v1
kind: Pod
metadata:
  name: mysql-env-secret

spec:
  containers:
    - name: mysql
      image: mysql:5.7
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-auth
              key: password
