apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - name: webserver
          image: nginx:1.16
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 80
          
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 400Mi
          
