apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-tls
spec:
  containers:
    - name: webserver
      image: nginx:1.16

      volumeMounts:
        - name: nginxconf
          mountPath: /etc/nginx/conf.d/
        - name: nginxcert
          mountPath: /etc/nginx/certs/

  volumes:
    - name: nginxconf
      configMap:
        name: nginx-ssl-host
        items:
          - key: nginx.conf
            path: abc.chascup.com.conf
            mode: 0644

    - name: nginxcert
      secret:
        secretName: abc-chasecup-com-tls

