apiVersion: v1
kind: Pod
metadata:
  name: pod-env-cm
spec:
  containers:
    - name: apps
      image: oldxu3957/demoapp:v1.0
      imagePullPolicy: IfNotPresent

      env:
        - name: NUMBER_PEOPLE
          valueFrom:
            configMapKeyRef:
              name: demo--3
              key: abc
        - name: WOMEN_NUMBER
          valueFrom:
            configMapKeyRef:
              name: demo--3
              key: xxx
              
