apiVersion: v1
kind: Pod
metadata:
  name: redis-server
spec:
  containers:
    - name: redis-server
      image: redis 
      imagePullPolicy: IfNotPresent
      command:
        - redis-server
        - "/redis-master/redis.conf"
      
      volumeMounts:
        - name: config
          mountPath: /redis-master/redis.conf
          subPath: redis-config
  
  volumes:
    - name: config
      configMap:
        name: exam-redis-conf
